<?php

define('RESUME_PERM_VIEW', 'view resumes');

function resume_access_node_grants($account, $op) {
  global $user;

  $grants = array();
  if ($op == 'view') {
    if (user_access(RESUME_PERM_VIEW, $account)) {
      $grants['resume_view'] = array(1);
    }
    $grants['resume_owner'] = array($user->uid);
  }
  return $grants;
}

function resume_access_node_access_records($node) {
  $grants = array();
  if (variable_get(RESUME_NODE_TYPE . $node->type, 0)) {
    $grants[] = array(
      'realm' => 'resume_view',
      'gid' => 1,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    );
    $grants[] = array(
      'realm' => 'resume_owner',
      'gid' => $node->uid ,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    );
  }
  return $grants;
}

function resume_access_permission() {
  return array(
    'view resumes' => array(
      'title' => t('View resumes'),
      'description' => t('Access for view resumes'),
    ),
  );
}
